# Generated by Django 4.2.2 on 2023-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_rename_person_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Возраст'),
        ),
    ]
