# Generated by Django 4.2.2 on 2023-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='')),
                ('lastname', models.CharField(max_length=50, verbose_name='')),
                ('birthday', models.DateField(verbose_name='')),
                ('position', models.CharField(max_length=50, verbose_name='')),
                ('education', models.CharField(choices=[('middle', 'middle'), ('high', 'high'), ('professional', 'профессиональное')], max_length=30)),
            ],
        ),
    ]
