# Generated by Django 4.2.3 on 2023-07-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_employee_options_alter_employee_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('черный', 'черный'), ('белый', 'белый'), ('желтый', 'желтый'), ('красный', 'красный'), ('зеленый', 'зеленый'), ('синий', 'синий')], default=None, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.car_brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car_color'),
        ),
    ]
