# Generated by Django 4.2.3 on 2023-07-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_car_brand_car_color_alter_car_brand_alter_car_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='car_color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
    ]
