# Generated by Django 4.2.3 on 2023-07-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('черный', 'черный'), ('белый', 'белый'), ('желтый', 'желтый'), ('красный', 'красный'), ('зеленый', 'зеленый'), ('синий', 'синий')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Car_color',
        ),
    ]
